# Generated by Django 4.2.4 on 2023-08-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, help_text='Ingrese sin puntos', max_length=8, null=True, verbose_name='D.N.I.')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField(help_text='dia/mes/año', max_length=6, verbose_name='Fecha de nacimiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], default='F', max_length=10, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Soltero'), ('V', 'Viudo'), ('O', 'Otro')], default='S', max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ('apellido', 'nombre'),
            },
        ),
    ]
