# Generated by Django 4.2.4 on 2023-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Email',
            field=models.EmailField(default='Ejemplo@gmail.com', max_length=250),
        ),
        migrations.AddField(
            model_name='persona',
            name='vive',
            field=models.BooleanField(default=True),
        ),
    ]
