# Generated by Django 4.2.4 on 2023-08-29 22:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas2', '0003_alter_persona_estado_civil_alter_persona_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='legajo',
            field=ckeditor.fields.RichTextField(default='legajo de persona '),
        ),
    ]
