# Generated by Django 4.2.4 on 2023-10-04 04:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas2', '0004_persona_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='imagenes/avatar.png', upload_to='imagenes/', verbose_name='Foto 4x4'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='legajo',
            field=ckeditor.fields.RichTextField(default='legajo de persona'),
        ),
    ]
