# Generated by Django 4.2.4 on 2023-10-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas2', '0005_persona_foto_alter_persona_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='imagenes/avatar.png', max_length=254, upload_to='imagenes/', verbose_name='Foto 4x4'),
        ),
    ]
