# Generated by Django 4.2.4 on 2023-10-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas2', '0006_alter_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('mensaje', models.TextField(default='escriba su mensaje ', max_length=250)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='media/imagenes/avatar.png', max_length=254, upload_to='media/imagenes/', verbose_name='Foto 4x4'),
        ),
    ]
